name: 'klaviyo'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.20.0"]


vars:
  klaviyo:
    event_table: "{{ ref( 'stg_klaviyo__event') }}" 
    campaign: "{{ ref( 'stg_klaviyo__campaign') }}" 
    flow: "{{ ref( 'stg_klaviyo__flow') }}" 
    integration: "{{ ref( 'stg_klaviyo__integration') }}" 
    person: "{{ ref( 'stg_klaviyo__person') }}" 
    metric: "{{ ref( 'stg_klaviyo__metric') }}" 

    klaviyo__email_attribution_lookback: 120 # hours - 5 days
    klaviyo__sms_attribution_lookback: 24 # hours
    klaviyo__event_attribution_filter: "lower(type) in ('opened email', 'clicked email', 'clicked sms')"

    klaviyo__pivot_conversion_filter: "integration_name != 'Mailchimp'"


  klaviyo_source:
    klaviyo__event_pass_through_columns:
      - name: property_subject
        alias: subject_line
    klaviyo__person_pass_through_columns: []

models: 
  klaviyo:
    # intermediate:
    #   +materialized: view
    +materialized: table

profile: klaviyo